[workspace]
resolver = "2"
members = [
  "cfc_crypto",
  "examples/square_enclave_app",
  "examples/square_service",
  "examples/sum_enclave_app",
  "examples/sum_service",
  "ledger_enclave_app",
  "ledger_service",
  "pipeline_transforms",
  "third_party/federated_compute",
]

[workspace.dependencies]
micro_rpc = { git = "https://github.com/project-oak/oak", rev = "6a8fdcfaada3b4e68c15f80e5e41827515338fcc" }
micro_rpc_build = { git = "https://github.com/project-oak/oak", rev = "6a8fdcfaada3b4e68c15f80e5e41827515338fcc" }
oak_attestation = { git = "https://github.com/project-oak/oak", rev = "6a8fdcfaada3b4e68c15f80e5e41827515338fcc" }
oak_attestation_verification = { git = "https://github.com/project-oak/oak", rev = "6a8fdcfaada3b4e68c15f80e5e41827515338fcc" }
oak_proto_rust = { git = "https://github.com/project-oak/oak", rev = "6a8fdcfaada3b4e68c15f80e5e41827515338fcc" }
oak_restricted_kernel_sdk = { git = "https://github.com/project-oak/oak", rev = "6a8fdcfaada3b4e68c15f80e5e41827515338fcc" }
