[workspace]
resolver = "2"
members = [
  "cfc_crypto",
  "examples/square_enclave_app",
  "examples/square_service",
  "examples/sum_enclave_app",
  "examples/sum_service",
  "ledger_enclave_app",
  "ledger_service",
  "pipeline_transforms",
  "third_party/federated_compute",
]

[workspace.dependencies]
micro_rpc = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
micro_rpc_build = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
oak_attestation_verification = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
oak_enclave_runtime_support = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
oak_channel = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
oak_core = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
oak_restricted_kernel_interface = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
oak_restricted_kernel_sdk = { git = "https://github.com/project-oak/oak", rev = "a103bcad4ca2d98dbfd6af36a8794649037b0f03" }
