[workspace]
resolver = "2"
members = [
  "cfc_crypto",
  "examples/square_enclave_app",
  "examples/square_service",
  "examples/sum_enclave_app",
  "examples/sum_service",
  "ledger_enclave_app",
  "ledger_service",
  "pipeline_transforms",
  "third_party/federated_compute",
]

[workspace.dependencies]
micro_rpc = { git = "https://github.com/project-oak/oak", rev = "704f81ed6310dfed448670b9fcdeb7ab6cfc78d1" }
micro_rpc_build = { git = "https://github.com/project-oak/oak", rev = "704f81ed6310dfed448670b9fcdeb7ab6cfc78d1" }
oak_channel = { git = "https://github.com/project-oak/oak", rev = "704f81ed6310dfed448670b9fcdeb7ab6cfc78d1" }
oak_core = { git = "https://github.com/project-oak/oak", rev = "704f81ed6310dfed448670b9fcdeb7ab6cfc78d1" }
oak_proto_rust = { git = "https://github.com/project-oak/oak", rev = "704f81ed6310dfed448670b9fcdeb7ab6cfc78d1" }
oak_restricted_kernel_sdk = { git = "https://github.com/project-oak/oak", rev = "704f81ed6310dfed448670b9fcdeb7ab6cfc78d1" }
