[workspace]
resolver = "2"
members = [
  "cfc_crypto",
  "examples/square_enclave_app",
  "examples/square_service",
  "examples/sum_enclave_app",
  "examples/sum_service",
  "ledger_enclave_app",
  "ledger_service",
  "pipeline_transforms",
  "third_party/federated_compute",
]

[workspace.dependencies]
micro_rpc = { git = "https://github.com/project-oak/oak", rev = "bf694d851b0472398276c7e0f57da9c2d004e7ad" }
micro_rpc_build = { git = "https://github.com/project-oak/oak", rev = "bf694d851b0472398276c7e0f57da9c2d004e7ad" }
oak_attestation = { git = "https://github.com/project-oak/oak", rev = "bf694d851b0472398276c7e0f57da9c2d004e7ad" }
oak_proto_rust = { git = "https://github.com/project-oak/oak", rev = "bf694d851b0472398276c7e0f57da9c2d004e7ad" }
oak_restricted_kernel_sdk = { git = "https://github.com/project-oak/oak", rev = "bf694d851b0472398276c7e0f57da9c2d004e7ad" }
