[workspace]
resolver = "2"
members = [
  "cfc_crypto",
  "examples/square_enclave_app",
  "examples/square_service",
  "examples/sum_enclave_app",
  "examples/sum_service",
  "ledger_enclave_app",
  "ledger_service",
  "pipeline_transforms",
  "third_party/federated_compute",
]

[workspace.dependencies]
micro_rpc = { git = "https://github.com/project-oak/oak", rev = "d90298ffe2eb828507dd1d71bdc13d3d7050a64f" }
micro_rpc_build = { git = "https://github.com/project-oak/oak", rev = "d90298ffe2eb828507dd1d71bdc13d3d7050a64f" }
oak_enclave_runtime_support = { git = "https://github.com/project-oak/oak", rev = "d90298ffe2eb828507dd1d71bdc13d3d7050a64f" }
oak_channel = { git = "https://github.com/project-oak/oak", rev = "d90298ffe2eb828507dd1d71bdc13d3d7050a64f" }
oak_core = { git = "https://github.com/project-oak/oak", rev = "d90298ffe2eb828507dd1d71bdc13d3d7050a64f" }
oak_restricted_kernel_interface = { git = "https://github.com/project-oak/oak", rev = "d90298ffe2eb828507dd1d71bdc13d3d7050a64f" }
oak_restricted_kernel_sdk = { git = "https://github.com/project-oak/oak", rev = "d90298ffe2eb828507dd1d71bdc13d3d7050a64f" }
