command = [
  "sh",
  "-c",
  "GITHUB_ACTION=\"provenance\" scripts/setup_build_env.sh && GITHUB_ACTION=\"provenance\" BINARY_OUTPUTS_DIR=\"binaries\" scripts/bazel_build.sh release"
]
artifact_path = "binaries/*"
