command = [
  "sh",
  "-c",
  "GITHUB_ACTION=\"provenance\" scripts/setup_build_env.sh && cargo build --release --package ledger_enclave_app"
]
artifact_path = "target/x86_64-unknown-none/release/ledger_enclave_app"
