command = [
  "sh",
  "-c",
  "GITHUB_ACTION=\"provenance\" scripts/setup_build_env.sh && cargo build --release --package square_enclave_app"
]
artifact_path = "target/x86_64-unknown-none/release/square_enclave_app"
