# Copyright 2023 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Directly managed dependencies
################################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "pypi_compat",
    path = "third_party/pypi_compat",
)

# go/keep-sorted start block=yes newline_separated=yes ignore_prefixes=git_repository,http_archive
http_archive(
    name = "boringssl",
    integrity = "sha256-YfmrrozMej0Kon25c2SrYYc4NEHI0R3+MVBlzWEsXo8=",
    strip_prefix = "boringssl-34492c89a8e381e0e856a686cc71b1eb5bd728db",
    url = "https://github.com/google/boringssl/archive/34492c89a8e381e0e856a686cc71b1eb5bd728db.tar.gz",
)

http_archive(
    name = "confidential-federated-compute",
    integrity = "sha256-AoScGBLMs1W6xwGvyYBlyXjDNxw1BLHmkzWX+zrwWOM=",
    # Adds flat_hash_map dependency to containers:session required by strict Clang Modules compilation.
    patches = [
        "//third_party/confidential_federated_compute:protobuf.patch",
    ],
    repo_mapping = {
        "@federated-compute": "@federated_compute",
    },
    strip_prefix = "confidential-federated-compute-21963d47355f5ba8685d8f1078bd25b3f619af66",
    url = "https://github.com/google-parfait/confidential-federated-compute/archive/21963d47355f5ba8685d8f1078bd25b3f619af66.tar.gz",
)

http_archive(
    name = "confidential-federated-compute-program",
    integrity = "sha256-BPh599WH8kzqXlZwPJSxMF3bhHzOLIFtDEk9Kp1r9Qc=",
    repo_mapping = {
        "@federated-compute": "@federated_compute",
    },
    strip_prefix = "confidential-federated-compute-623819024308093e4c30c9e5d030bca62d7a5b15/program_containers",
    url = "https://github.com/google-parfait/confidential-federated-compute/archive/623819024308093e4c30c9e5d030bca62d7a5b15.tar.gz",
)

http_archive(
    name = "federated_compute",
    integrity = "sha256-FJkPuzY5USjy+P8blFTMIryWsThv8eJbzRyi1N/kZrQ=",
    patches = [
        "@confidential-federated-compute-program//third_party/federated_compute:absl.patch",
        "@confidential-federated-compute-program//third_party/federated_compute:protobuf.patch",
        "//third_party/federated_compute:dpmf.patch",
    ],
    repo_mapping = {"@com_google_googletest": "@googletest"},
    strip_prefix = "federated-compute-4166b880b9e8467a829f678a17f4122fdb76f4f1",
    url = "https://github.com/google/federated-compute/archive/4166b880b9e8467a829f678a17f4122fdb76f4f1.tar.gz",
)

http_archive(
    name = "federated_language",
    integrity = "sha256-MMOkhh5jtKwrTRclFSd2OpoM1eBJpbEAOO1OCcQ3SGI=",
    patches = [
        "@org_tensorflow_federated//third_party/federated_language:numpy.patch",
        "@org_tensorflow_federated//third_party/federated_language:proto_library_loads.patch",
        "@org_tensorflow_federated//third_party/federated_language:python_deps.patch",
        "@org_tensorflow_federated//third_party/federated_language:structure_visibility.patch",
        "@org_tensorflow_federated//third_party/federated_language:remove_compile_pip_requirements.patch",
    ],
    repo_mapping = {
        "@federated_language_pypi": "@pypi",
        "@protobuf": "@com_google_protobuf",
    },
    strip_prefix = "federated-language-0.5.3",
    url = "https://github.com/google-parfait/federated-language/archive/refs/tags/v0.5.3.tar.gz",
)

http_archive(
    name = "federated_language_jax",
    integrity = "sha256-mmtwW92hlfmBJE/Mp6qXj+hEqwv2kv3TR7YkdqhwH+M=",
    patches = [
        "//third_party/federated_language_jax:bazel_deps.patch",
        "//third_party/federated_language_jax:computation_visibility.patch",
    ],
    repo_mapping = {
        "@abseil-cpp": "@com_google_absl",
        "@federated_language_jax_pypi": "@pypi",
    },
    strip_prefix = "federated-language-jax-fe45ed06b2f260874c50b56d727d5bc509df685f",
    url = "https://github.com/google-parfait/federated-language-jax/archive/fe45ed06b2f260874c50b56d727d5bc509df685f.tar.gz",
)

http_archive(
    name = "googletest",
    sha256 = "8ad598c73ad796e0d8280b082cebd82a630d73e73cd3c70057938a6501bba5d7",
    strip_prefix = "googletest-1.14.0",
    url = "https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz",
)

http_archive(
    name = "jax_privacy",
    integrity = "sha256-hCExiV+6kNdxdgv7E9VcIyVkJoNsZAUiStaArWUD6xo=",
    patches = [
        "//third_party/jax_privacy:dpmf.patch",
    ],
    strip_prefix = "jax_privacy-7ad9c12b72926951854ca1868352f8b33f829080",
    url = "https://github.com/google-deepmind/jax_privacy/archive/7ad9c12b72926951854ca1868352f8b33f829080.tar.gz",
)

git_repository(
    name = "libcppbor",
    build_file = "@federated_compute//third_party:libcppbor.BUILD.bzl",
    commit = "20d2be8672d24bfb441d075f82cc317d17d601f8",
    patches = ["//third_party/libcppbor:libcppbor.patch"],
    remote = "https://android.googlesource.com/platform/external/libcppbor",
)

http_archive(
    name = "oak",
    integrity = "sha256-WHDrpSMKtd1NdzCvT7odZKseG0qqnPNfWCiw0CkmHXY=",
    patches = [
        "//third_party/oak:oak_attestation_verification.patch",
        "//third_party/oak:protobuf.patch",
        "//third_party/oak:session_binder.patch",
    ],
    strip_prefix = "oak-cb4ce74ed6e9e38f05def5af67207517fe4663a2",
    url = "https://github.com/project-oak/oak/archive/cb4ce74ed6e9e38f05def5af67207517fe4663a2.tar.gz",
)

http_archive(
    name = "org_tensorflow",
    patches = [
        "//third_party/org_tensorflow:cython.patch",
        "//third_party/org_tensorflow:internal_visibility.patch",
        "//third_party/org_tensorflow:xla_xxd.patch",
        "//third_party/org_tensorflow:xla_copts.patch",
        "//third_party/org_tensorflow:xla_asserts.patch",
    ],
    repo_mapping = {
        "@com_google_googletest": "@googletest",
    },
    sha256 = "ef3568bb4865d6c1b2564fb5689c19b6b9a5311572cd1f2ff9198636a8520921",
    strip_prefix = "tensorflow-2.21.0",
    url = "https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.21.0.tar.gz",
)

http_archive(
    name = "org_tensorflow_federated",
    integrity = "sha256-fSgxmFfrisZeGWStV+Hv0SdFXvSPeW+q0ZH9shhXQK8=",
    patch_args = ["-p1"],
    patches = [
        "//third_party/org_tensorflow_federated:tff_tf_combined_fixes.patch",
    ],
    repo_mapping = {"@pypi": "@pypi_compat"},
    strip_prefix = "tensorflow-federated-189fb8e13aa97ff11653a95de631b305420f9a5a",
    url = "https://github.com/google-parfait/tensorflow-federated/archive/189fb8e13aa97ff11653a95de631b305420f9a5a.tar.gz",
)

# Required by `pybind11_bazel`.
http_archive(
    name = "pybind11",
    build_file = "@pybind11_bazel//:pybind11-BUILD.bazel",
    sha256 = "e08cb87f4773da97fa7b5f035de8763abc656d87d5773e62f6da0587d1f0ec20",
    strip_prefix = "pybind11-2.13.6",
    url = "https://github.com/pybind/pybind11/archive/refs/tags/v2.13.6.tar.gz",
)

http_archive(
    name = "pybind11_bazel",
    sha256 = "cae680670bfa6e82703c03f2a3c995408cdcbf43616d7bdd198ef45d3c327731",
    strip_prefix = "pybind11_bazel-2.13.6",
    url = "https://github.com/pybind/pybind11_bazel/archive/refs/tags/v2.13.6.tar.gz",
)

http_archive(
    name = "rules_cc",
    patch_args = ["-p1"],
    patches = [
        # Patch rules_cc to be compatible with the older version of protobuf we use.
        "@rules_rust//rust/private/3rdparty:rules_cc.patch",
    ],
    sha256 = "abc605dd850f813bb37004b77db20106a19311a96b2da1c92b789da529d28fe1",
    strip_prefix = "rules_cc-0.0.17",
    url = "https://github.com/bazelbuild/rules_cc/releases/download/0.0.17/rules_cc-0.0.17.tar.gz",
)

http_archive(
    name = "rules_oci",
    patches = [
        "//third_party/rules_oci:zot_rbe.patch",
    ],
    sha256 = "4a276e9566c03491649eef63f27c2816cc222f41ccdebd97d2c5159e84917c3b",
    strip_prefix = "rules_oci-1.7.4",
    url = "https://github.com/bazel-contrib/rules_oci/releases/download/v1.7.4/rules_oci-v1.7.4.tar.gz",
)

http_archive(
    name = "rules_proto",
    sha256 = "6fb6767d1bef535310547e03247f7518b03487740c11b6c6adb7952033fe1295",
    strip_prefix = "rules_proto-6.0.2",
    url = "https://github.com/bazelbuild/rules_proto/releases/download/6.0.2/rules_proto-6.0.2.tar.gz",
)

http_archive(
    name = "rules_python",
    sha256 = "f2e80f97f9c0b82e2489e61e725df1e6bdaf16c4dacf5e26b95668787164baff",
    strip_prefix = "rules_python-1.6.1",
    url = "https://github.com/bazel-contrib/rules_python/releases/download/1.6.1/rules_python-1.6.1.tar.gz",
)

http_archive(
    name = "rules_rust",
    integrity = "sha256-CeF7R8AVBGVjGqMZ8nQnYKQ+3tqy6cAS+R0K4u/wImg=",
    url = "https://github.com/bazelbuild/rules_rust/releases/download/0.59.2/rules_rust-0.59.2.tar.gz",
)

http_archive(
    name = "rules_rust_bindgen",
    integrity = "sha256-CeF7R8AVBGVjGqMZ8nQnYKQ+3tqy6cAS+R0K4u/wImg=",
    strip_prefix = "extensions/bindgen",
    url = "https://github.com/bazelbuild/rules_rust/releases/download/0.59.2/rules_rust-0.59.2.tar.gz",
)

http_archive(
    name = "sysroot",
    # Build provenance available at https://search.sigstore.dev/?hash=<sha256>.
    # To make this lookup easier, we use `sha256` instead of `integrity`.
    sha256 = "86ccf9ea2360237ecad01633a86d566ed16e137daf986320ef91ec295ea5f679",
    url = "https://github.com/google-parfait/confidential-federated-compute/releases/download/sysroot-20260311/sysroot.tar.xz",
)

http_archive(
    name = "toolchains_llvm",
    sha256 = "fded02569617d24551a0ad09c0750dc53a3097237157b828a245681f0ae739f8",
    strip_prefix = "toolchains_llvm-v1.4.0",
    url = "https://github.com/bazel-contrib/toolchains_llvm/releases/download/v1.4.0/toolchains_llvm-v1.4.0.tar.gz",
)

# TensorFlow pins an old version of upb that's compatible with their old
# version of gRPC, but not with the newer version we use. Pin the version that
# would be added by gRPC 1.50.0.
http_archive(
    name = "upb",
    sha256 = "017a7e8e4e842d01dba5dc8aa316323eee080cd1b75986a7d1f94d87220e6502",
    strip_prefix = "upb-e4635f223e7d36dfbea3b722a4ca4807a7e882e2",
    urls = [
        "https://storage.googleapis.com/grpc-bazel-mirror/github.com/protocolbuffers/upb/archive/e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz",
        "https://github.com/protocolbuffers/upb/archive/e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz",
    ],
)
# go/keep-sorted end

################################################################################
# Stubbed out dependencies
################################################################################

load("@confidential-federated-compute-program//:stub_repo.bzl", "stub_repo")

# go/keep-sorted start block=yes newline_separated=yes
http_archive(
    name = "bazel_features",
    sha256 = "4fd9922d464686820ffd8fcefa28ccffa147f7cdc6b6ac0d8b07fde565c65d66",
    strip_prefix = "bazel_features-1.25.0",
    url = "https://github.com/bazel-contrib/bazel_features/releases/download/v1.25.0/bazel_features-v1.25.0.tar.gz",
)

http_archive(
    name = "bazel_skylib",
    sha256 = "bc283cdfcd526a52c3201279cda4bc298652efa898b10b4db0837dc51652756f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
    ],
)

http_archive(
    name = "com_google_absl",
    sha256 = "d1abe9da2003e6cbbd7619b0ced3e52047422f4f4ac6c66a9bef5d2e99fea837",
    strip_prefix = "abseil-cpp-d38452e1ee03523a208362186fd42248ff2609f6",
    urls = [
        "https://github.com/abseil/abseil-cpp/archive/d38452e1ee03523a208362186fd42248ff2609f6.tar.gz",
    ],
)

http_archive(
    name = "com_google_protobuf",
    repo_mapping = {
        "@abseil-cpp": "@com_google_absl",
        "@protobuf_pip_deps": "@pypi",
        "@system_python": "@python",
    },
    sha256 = "6e09bbc950ba60c3a7b30280210cd285af8d7d8ed5e0a6ed101c72aff22e8d88",
    strip_prefix = "protobuf-6.31.1",
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/refs/tags/v6.31.1.zip",
    ],
)

http_archive(
    name = "rules_java",
    sha256 = "1b30698d89dccd9dc01b1a4ad7e9e5c6e669cdf1918dbb050334e365b40a1b5e",
    url = "https://github.com/bazelbuild/rules_java/releases/download/8.16.1/rules_java-8.16.1.tar.gz",
)

stub_repo(
    name = "com_github_grpc_grpc_kotlin",
    rules = {":kt_jvm_grpc.bzl": ["kt_jvm_grpc_library"]},
)

stub_repo(
    name = "io_grpc_grpc_java",
    rules = {":java_grpc_library.bzl": ["java_grpc_library"]},
)
# go/keep-sorted end

load("@bazel_features//:deps.bzl", "bazel_features_deps")

bazel_features_deps()

################################################################################
# Transitive dependencies managed via macros
################################################################################

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies")

rules_rust_dependencies()

load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")

rules_java_dependencies()

# Call py_repositories() first so rules_python can setup any state
# subsequent things might need. See
# https://github.com/bazelbuild/rules_python/issues/1560
load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python",
    python_version = "3.12",  # Keep in sync with repo env set in .bazelrc
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pypi",
    extra_pip_args = [
        "--index-url",
        "https://pypi.org/simple",
        "--only-binary=:all:",  # Forces PyPI to download pre-compiled static wheels only
    ],
    python_interpreter_target = "@python_host//:python",
    requirements_lock = "//:requirements_lock.txt",
)

load("@pypi//:requirements.bzl", "install_deps")

install_deps()

load("@org_tensorflow//third_party/py:python_init_repositories.bzl", "python_init_repositories")

python_init_repositories(
    local_wheel_dist_folder = "dist",
    local_wheel_inclusion_list = [
        "tensorflow*",
        "tf_nightly*",
    ],
    local_wheel_workspaces = ["//:WORKSPACE"],
    requirements = {
        "3.12": "@org_tensorflow//:requirements_lock_3_12.txt",
    },
)

# The following is copied from TensorFlow's own WORKSPACE, see
# https://github.com/tensorflow/tensorflow/blob/v2.19.0-rc0/WORKSPACE#L68
load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")

tf_workspace3()

load(
    "@xla//third_party/py:python_wheel.bzl",
    "python_wheel_version_suffix_repository",
)

python_wheel_version_suffix_repository(name = "tf_wheel_version_suffix")

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")

tf_workspace2()

load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")

tf_workspace1()

load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")

tf_workspace0()

load(
    "@xla//third_party/gpus/cuda/hermetic:cuda_json_init_repository.bzl",
    "cuda_json_init_repository",
)

cuda_json_init_repository()

load(
    "@cuda_redist_json//:distributions.bzl",
    "CUDA_REDISTRIBUTIONS",
    "CUDNN_REDISTRIBUTIONS",
)
load(
    "@xla//third_party/gpus/cuda/hermetic:cuda_redist_init_repositories.bzl",
    "cuda_redist_init_repositories",
    "cudnn_redist_init_repository",
)

cuda_redist_init_repositories(
    cuda_redistributions = CUDA_REDISTRIBUTIONS,
)

cudnn_redist_init_repository(
    cudnn_redistributions = CUDNN_REDISTRIBUTIONS,
)

load(
    "@xla//third_party/gpus/cuda/hermetic:cuda_configure.bzl",
    "cuda_configure",
)

cuda_configure(name = "local_config_cuda")

load(
    "@xla//third_party/nccl/hermetic:nccl_redist_init_repository.bzl",
    "nccl_redist_init_repository",
)

nccl_redist_init_repository()

load(
    "@xla//third_party/nccl/hermetic:nccl_configure.bzl",
    "nccl_configure",
)

nccl_configure(name = "local_config_nccl")

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies")

rules_proto_dependencies()

load("@rules_proto//proto:setup.bzl", "rules_proto_setup")

rules_proto_setup()

load("@rules_proto//proto:toolchains.bzl", "rules_proto_toolchains")

rules_proto_toolchains()

load("@oak//bazel:repositories.bzl", "oak_toolchain_repositories")

oak_toolchain_repositories()

load("@oak//bazel/crates:patched_crates.bzl", "load_patched_crates")

load_patched_crates()

load("@oak//bazel/rust:defs.bzl", "setup_rust_dependencies")

setup_rust_dependencies()

load("@oak//bazel/crates:repositories.bzl", "create_oak_crate_repositories")

create_oak_crate_repositories()

load("@oak//bazel/crates:crates.bzl", "load_oak_crate_repositories")

load_oak_crate_repositories()

load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")

rules_oci_dependencies()

load("@rules_oci//oci:repositories.bzl", "LATEST_CRANE_VERSION", "LATEST_ZOT_VERSION", "oci_register_toolchains")

oci_register_toolchains(
    name = "oci",
    crane_version = LATEST_CRANE_VERSION,
    zot_version = LATEST_ZOT_VERSION,
)

load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "distroless_cc_debian12",
    digest = "sha256:6714977f9f02632c31377650c15d89a7efaebf43bab0f37c712c30fc01edb973",
    image = "gcr.io/distroless/cc-debian12",
    platforms = ["linux/amd64"],
)

oci_pull(
    name = "python_3_12_slim_bookworm",
    digest = "sha256:519591d6871b7bc437060736b9f7456b8731f1499a57e22e6c285135ae657bf7",
    image = "python",
    platforms = ["linux/amd64"],
)

load("@toolchains_llvm//toolchain:deps.bzl", "bazel_toolchain_dependencies")

bazel_toolchain_dependencies()

load("@toolchains_llvm//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    # Use LLVM version 14 as version 13 has a bug which causes asan to fail:
    # https://github.com/llvm/llvm-project/issues/51620
    llvm_version = "14.0.0",
    # Using the PyPi tensorflow package requires using libstdc++ to ensure the
    # right C++ ABI.
    stdlib = {"linux-x86_64": "stdc++"},
    sysroot = {"linux-x86_64": "@sysroot"},
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")

llvm_register_toolchains()
