# Copyright 2023 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Directly managed dependencies
################################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "pypi_compat",
    path = "third_party/pypi_compat",
)

# go/keep-sorted start block=yes newline_separated=yes ignore_prefixes=git_repository,http_archive
http_archive(
    name = "bazel_features",
    sha256 = "4fd9922d464686820ffd8fcefa28ccffa147f7cdc6b6ac0d8b07fde565c65d66",
    strip_prefix = "bazel_features-1.25.0",
    url = "https://github.com/bazel-contrib/bazel_features/releases/download/v1.25.0/bazel_features-v1.25.0.tar.gz",
)

http_archive(
    name = "bazel_skylib",
    sha256 = "bc283cdfcd526a52c3201279cda4bc298652efa898b10b4db0837dc51652756f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
    ],
)

http_archive(
    name = "boringssl",
    integrity = "sha256-YfmrrozMej0Kon25c2SrYYc4NEHI0R3+MVBlzWEsXo8=",
    strip_prefix = "boringssl-34492c89a8e381e0e856a686cc71b1eb5bd728db",
    url = "https://github.com/google/boringssl/archive/34492c89a8e381e0e856a686cc71b1eb5bd728db.tar.gz",
)

# Pin the same version of gRPC as TF 2.21 but add a patch to fix build errors.
http_archive(
    name = "com_github_grpc_grpc",
    patch_args = ["-p1"],
    patches = [
        "//third_party/grpc:grpc.patch",
    ],
    sha256 = "dd6a2fa311ba8441bbefd2764c55b99136ff10f7ea42954be96006a2723d33fc",
    strip_prefix = "grpc-1.74.0",
    url = "https://github.com/grpc/grpc/archive/refs/tags/v1.74.0.tar.gz",
)

http_archive(
    name = "com_google_absl",
    integrity = "sha256-aZqRgScSBhTdlLtmgvQYeqnT/HdJvAjf/lMceYY8Crg=",
    strip_prefix = "abseil-cpp-2de04920ef4c48926b696d4926224f12d295d8be",
    urls = [
        "https://github.com/abseil/abseil-cpp/archive/2de04920ef4c48926b696d4926224f12d295d8be.tar.gz",
    ],
)

http_archive(
    name = "com_google_protobuf",
    integrity = "sha256-/aEyywyGQAOBwK8f6YvQ93XLVmyyR83MEF40TgCsww4=",
    repo_mapping = {
        "@abseil-cpp": "@com_google_absl",
        "@system_python": "@python",
    },
    strip_prefix = "protobuf-33.1",
    urls = [
        "https://github.com/protocolbuffers/protobuf/releases/download/v33.1/protobuf-33.1.tar.gz",
    ],
)

# Pin the same version of re2 as TF 2.21 but add a patch to fix build errors.
http_archive(
    name = "com_googlesource_code_re2",
    patches = [
        "//third_party/re2:memchr.patch",
    ],
    sha256 = "ef516fb84824a597c4d5d0d6d330daedb18363b5a99eda87d027e6bdd9cba299",
    strip_prefix = "re2-03da4fc0857c285e3a26782f6bc8931c4c950df4",
    url = "https://github.com/google/re2/archive/03da4fc0857c285e3a26782f6bc8931c4c950df4.tar.gz",
)

http_archive(
    name = "confidential_federated_compute",
    integrity = "sha256-5qg/ClAMJxo8SyxGBo7sjyk43Q5gsI5RbZBSC+iqs4g=",
    strip_prefix = "confidential-federated-compute-cf6389b18237a091a4cf31e8e7509663be5d0c5e",
    url = "https://github.com/google-parfait/confidential-federated-compute/archive/cf6389b18237a091a4cf31e8e7509663be5d0c5e.tar.gz",
)

http_archive(
    name = "confidential_federated_compute_program",
    integrity = "sha256-5qg/ClAMJxo8SyxGBo7sjyk43Q5gsI5RbZBSC+iqs4g=",
    strip_prefix = "confidential-federated-compute-cf6389b18237a091a4cf31e8e7509663be5d0c5e/program_containers",
    url = "https://github.com/google-parfait/confidential-federated-compute/archive/cf6389b18237a091a4cf31e8e7509663be5d0c5e.tar.gz",
)

http_archive(
    name = "federated_compute",
    integrity = "sha256-dQ41bouZrA2ws9FZ7T6de32S2CWWOv4Bc6QAjqwZX/o=",
    patch_cmds = [
        "sed -i 's|@pypi//jax_privacy|@jax_privacy//jax_privacy|g' fcp/confidentialcompute/python/BUILD",
        "sed -i 's|\"@pypi//tensorflow\"|\"@pypi//tensorflow_cpu\"|g' fcp/confidentialcompute/python/BUILD",
    ],
    repo_mapping = {"@com_google_googletest": "@googletest"},
    strip_prefix = "federated-compute-7c7cd41d5038da2637ae9b0ec7f7875fbfe9cafc",
    url = "https://github.com/google/federated-compute/archive/7c7cd41d5038da2637ae9b0ec7f7875fbfe9cafc.tar.gz",
)

http_archive(
    name = "federated_language",
    patches = [
        "@org_tensorflow_federated//third_party/federated_language:proto_library_loads.patch",
        "@confidential_federated_compute_program//third_party/federated_language:structure_visibility.patch",
        "@confidential_federated_compute_program//third_party/federated_language:python_toolchain.patch",
    ],
    repo_mapping = {
        "@federated_language_pypi": "@pypi",
        "@protobuf": "@com_google_protobuf",
    },
    sha256 = "30c3a4861e63b4ac2b4d17251527763a9a0cd5e049a5b10038ed4e09c4374862",
    strip_prefix = "federated-language-0.5.3",
    url = "https://github.com/google-parfait/federated-language/archive/refs/tags/v0.5.3.tar.gz",
)

http_archive(
    name = "googletest",
    sha256 = "8ad598c73ad796e0d8280b082cebd82a630d73e73cd3c70057938a6501bba5d7",
    strip_prefix = "googletest-1.14.0",
    url = "https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz",
)

http_archive(
    name = "jax_privacy",
    integrity = "sha256-zjVOFalwAsN7TWeW27wAtfAkMbU8Lk+cqwb6iwUrFCA=",
    patches = [
        "@confidential_federated_compute_program//third_party/jax_privacy:package.patch",
    ],
    strip_prefix = "jax_privacy-03f69a78171369361df19230274979b59b3c4f36",
    url = "https://github.com/google-deepmind/jax_privacy/archive/03f69a78171369361df19230274979b59b3c4f36.tar.gz",
)

git_repository(
    name = "libcppbor",
    build_file = "@federated_compute//third_party:libcppbor.BUILD.bzl",
    commit = "20d2be8672d24bfb441d075f82cc317d17d601f8",
    patches = ["//third_party/libcppbor:libcppbor.patch"],
    remote = "https://android.googlesource.com/platform/external/libcppbor",
)

http_archive(
    name = "oak",
    integrity = "sha256-WHDrpSMKtd1NdzCvT7odZKseG0qqnPNfWCiw0CkmHXY=",
    patches = [
        "//third_party/oak:oak_attestation_verification.patch",
        "//third_party/oak:session_binder.patch",
    ],
    strip_prefix = "oak-cb4ce74ed6e9e38f05def5af67207517fe4663a2",
    url = "https://github.com/project-oak/oak/archive/cb4ce74ed6e9e38f05def5af67207517fe4663a2.tar.gz",
)

http_archive(
    name = "org_tensorflow",
    patches = [
        "//third_party/org_tensorflow:cython.patch",
        "//third_party/org_tensorflow:internal_visibility.patch",
        "//third_party/org_tensorflow:xla_xxd.patch",
        "//third_party/org_tensorflow:xla_copts.patch",
        "//third_party/org_tensorflow:xla_asserts.patch",
        "//third_party/org_tensorflow:xla_custom_call_status.patch",
    ],
    repo_mapping = {
        "@com_google_googletest": "@googletest",
    },
    sha256 = "ef3568bb4865d6c1b2564fb5689c19b6b9a5311572cd1f2ff9198636a8520921",
    strip_prefix = "tensorflow-2.21.0",
    url = "https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.21.0.tar.gz",
)

http_archive(
    name = "org_tensorflow_federated",
    integrity = "sha256-fSgxmFfrisZeGWStV+Hv0SdFXvSPeW+q0ZH9shhXQK8=",
    patch_args = ["-p1"],
    patches = [
        "//third_party/org_tensorflow_federated:tff_tf_combined_fixes.patch",
    ],
    repo_mapping = {"@pypi": "@pypi_compat"},
    strip_prefix = "tensorflow-federated-189fb8e13aa97ff11653a95de631b305420f9a5a",
    url = "https://github.com/google-parfait/tensorflow-federated/archive/189fb8e13aa97ff11653a95de631b305420f9a5a.tar.gz",
)

http_archive(
    name = "pybind11",
    build_file = "@pybind11_bazel//:pybind11-BUILD.bazel",
    sha256 = "e08cb87f4773da97fa7b5f035de8763abc656d87d5773e62f6da0587d1f0ec20",
    strip_prefix = "pybind11-2.13.6",
    url = "https://github.com/pybind/pybind11/archive/refs/tags/v2.13.6.tar.gz",
)

http_archive(
    name = "pybind11_bazel",
    sha256 = "cae680670bfa6e82703c03f2a3c995408cdcbf43616d7bdd198ef45d3c327731",
    strip_prefix = "pybind11_bazel-2.13.6",
    url = "https://github.com/pybind/pybind11_bazel/archive/refs/tags/v2.13.6.tar.gz",
)

http_archive(
    name = "rules_cc",
    sha256 = "abc605dd850f813bb37004b77db20106a19311a96b2da1c92b789da529d28fe1",
    strip_prefix = "rules_cc-0.0.17",
    url = "https://github.com/bazelbuild/rules_cc/releases/download/0.0.17/rules_cc-0.0.17.tar.gz",
)

http_archive(
    name = "rules_java",
    sha256 = "1b30698d89dccd9dc01b1a4ad7e9e5c6e669cdf1918dbb050334e365b40a1b5e",
    url = "https://github.com/bazelbuild/rules_java/releases/download/8.16.1/rules_java-8.16.1.tar.gz",
)

http_archive(
    name = "rules_oci",
    sha256 = "b8db7ab889d501db33313620b2c8040dbb07e95c26a0fefe06004b35baf80e08",
    strip_prefix = "rules_oci-2.2.7",
    url = "https://github.com/bazel-contrib/rules_oci/releases/download/v2.2.7/rules_oci-v2.2.7.tar.gz",
)

http_archive(
    name = "rules_proto",
    sha256 = "6fb6767d1bef535310547e03247f7518b03487740c11b6c6adb7952033fe1295",
    strip_prefix = "rules_proto-6.0.2",
    url = "https://github.com/bazelbuild/rules_proto/releases/download/6.0.2/rules_proto-6.0.2.tar.gz",
)

http_archive(
    name = "rules_python",
    sha256 = "f2e80f97f9c0b82e2489e61e725df1e6bdaf16c4dacf5e26b95668787164baff",
    strip_prefix = "rules_python-1.6.1",
    url = "https://github.com/bazel-contrib/rules_python/releases/download/1.6.1/rules_python-1.6.1.tar.gz",
)

http_archive(
    name = "rules_rust",
    integrity = "sha256-CeF7R8AVBGVjGqMZ8nQnYKQ+3tqy6cAS+R0K4u/wImg=",
    url = "https://github.com/bazelbuild/rules_rust/releases/download/0.59.2/rules_rust-0.59.2.tar.gz",
)

http_archive(
    name = "rules_rust_bindgen",
    integrity = "sha256-CeF7R8AVBGVjGqMZ8nQnYKQ+3tqy6cAS+R0K4u/wImg=",
    strip_prefix = "extensions/bindgen",
    url = "https://github.com/bazelbuild/rules_rust/releases/download/0.59.2/rules_rust-0.59.2.tar.gz",
)

http_archive(
    name = "sysroot",
    # Build provenance available at https://search.sigstore.dev/?hash=<sha256>.
    # To make this lookup easier, we use `sha256` instead of `integrity`.
    sha256 = "86ccf9ea2360237ecad01633a86d566ed16e137daf986320ef91ec295ea5f679",
    url = "https://github.com/google-parfait/confidential-federated-compute/releases/download/sysroot-20260311/sysroot.tar.xz",
)

http_archive(
    name = "toolchains_llvm",
    sha256 = "fded02569617d24551a0ad09c0750dc53a3097237157b828a245681f0ae739f8",
    strip_prefix = "toolchains_llvm-v1.4.0",
    url = "https://github.com/bazel-contrib/toolchains_llvm/releases/download/v1.4.0/toolchains_llvm-v1.4.0.tar.gz",
)
# go/keep-sorted end

################################################################################
# Stubbed out dependencies
################################################################################

load("@confidential_federated_compute_program//:stub_repo.bzl", "stub_repo")

stub_repo(
    name = "com_github_grpc_grpc_kotlin",
    rules = {":kt_jvm_grpc.bzl": ["kt_jvm_grpc_library"]},
)

stub_repo(
    name = "io_grpc_grpc_java",
    rules = {":java_grpc_library.bzl": ["java_grpc_library"]},
)

load("@bazel_features//:deps.bzl", "bazel_features_deps")

bazel_features_deps()

################################################################################
# Transitive dependencies managed via macros
################################################################################

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies")

rules_rust_dependencies()

load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")

rules_java_dependencies()

# Call py_repositories() first so rules_python can setup any state
# subsequent things might need. See
# https://github.com/bazelbuild/rules_python/issues/1560
load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python",
    python_version = "3.12",  # Keep in sync with repo env set in .bazelrc
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pypi",
    extra_pip_args = [
        "--index-url",
        "https://pypi.org/simple",
        "--only-binary=:all:",  # Forces PyPI to download pre-compiled static wheels only
    ],
    python_interpreter_target = "@python_host//:python",
    requirements_lock = "//:requirements_lock.txt",
)

load("@pypi//:requirements.bzl", "install_deps")

install_deps()

load("@org_tensorflow//third_party/py:python_init_repositories.bzl", "python_init_repositories")

python_init_repositories(
    local_wheel_dist_folder = "dist",
    local_wheel_inclusion_list = [
        "tensorflow*",
        "tf_nightly*",
    ],
    local_wheel_workspaces = ["//:WORKSPACE"],
    requirements = {
        "3.12": "@org_tensorflow//:requirements_lock_3_12.txt",
    },
)

# The following is copied from TensorFlow's own WORKSPACE, see
# https://github.com/tensorflow/tensorflow/blob/v2.19.0-rc0/WORKSPACE#L68
load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")

tf_workspace3()

load(
    "@xla//third_party/py:python_wheel.bzl",
    "python_wheel_version_suffix_repository",
)

python_wheel_version_suffix_repository(name = "tf_wheel_version_suffix")

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")

tf_workspace2()

load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")

tf_workspace1()

load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")

tf_workspace0()

load(
    "@xla//third_party/gpus/cuda/hermetic:cuda_json_init_repository.bzl",
    "cuda_json_init_repository",
)

cuda_json_init_repository()

load(
    "@cuda_redist_json//:distributions.bzl",
    "CUDA_REDISTRIBUTIONS",
    "CUDNN_REDISTRIBUTIONS",
)
load(
    "@xla//third_party/gpus/cuda/hermetic:cuda_redist_init_repositories.bzl",
    "cuda_redist_init_repositories",
    "cudnn_redist_init_repository",
)

cuda_redist_init_repositories(
    cuda_redistributions = CUDA_REDISTRIBUTIONS,
)

cudnn_redist_init_repository(
    cudnn_redistributions = CUDNN_REDISTRIBUTIONS,
)

load(
    "@xla//third_party/gpus/cuda/hermetic:cuda_configure.bzl",
    "cuda_configure",
)

cuda_configure(name = "local_config_cuda")

load(
    "@xla//third_party/nccl/hermetic:nccl_redist_init_repository.bzl",
    "nccl_redist_init_repository",
)

nccl_redist_init_repository()

load(
    "@xla//third_party/nccl/hermetic:nccl_configure.bzl",
    "nccl_configure",
)

nccl_configure(name = "local_config_nccl")

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies")

rules_proto_dependencies()

load("@rules_proto//proto:setup.bzl", "rules_proto_setup")

rules_proto_setup()

load("@rules_proto//proto:toolchains.bzl", "rules_proto_toolchains")

rules_proto_toolchains()

load("@oak//bazel:repositories.bzl", "oak_toolchain_repositories")

oak_toolchain_repositories()

load("@oak//bazel/crates:patched_crates.bzl", "load_patched_crates")

load_patched_crates()

load("@oak//bazel/rust:defs.bzl", "setup_rust_dependencies")

setup_rust_dependencies()

load("@oak//bazel/crates:repositories.bzl", "create_oak_crate_repositories")

create_oak_crate_repositories()

load("@oak//bazel/crates:crates.bzl", "load_oak_crate_repositories")

load_oak_crate_repositories()

load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")

rules_oci_dependencies()

load("@aspect_bazel_lib//lib:repositories.bzl", "register_yq_toolchains")

register_yq_toolchains()

load("@rules_oci//oci:repositories.bzl", "oci_register_toolchains")

oci_register_toolchains(
    name = "oci",
)

load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "distroless_cc_debian12",
    digest = "sha256:6714977f9f02632c31377650c15d89a7efaebf43bab0f37c712c30fc01edb973",
    image = "gcr.io/distroless/cc-debian12",
    platforms = ["linux/amd64"],
)

oci_pull(
    name = "python_3_12_slim_bookworm",
    digest = "sha256:519591d6871b7bc437060736b9f7456b8731f1499a57e22e6c285135ae657bf7",
    image = "python",
    platforms = ["linux/amd64"],
)

load("@toolchains_llvm//toolchain:deps.bzl", "bazel_toolchain_dependencies")

bazel_toolchain_dependencies()

load("@toolchains_llvm//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    # Use LLVM version 14 as version 13 has a bug which causes asan to fail:
    # https://github.com/llvm/llvm-project/issues/51620
    llvm_version = "14.0.0",
    # Using the PyPi tensorflow package requires using libstdc++ to ensure the
    # right C++ ABI.
    stdlib = {"linux-x86_64": "stdc++"},
    sysroot = {"linux-x86_64": "@sysroot"},
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")

llvm_register_toolchains()
