name: Release sysroot

on:
  push:
    tags:
      - 'sysroot-*'

jobs:
  build:
    permissions:
      contents: write
      id-token: write
      attestations: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: toolchains/sysroot
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          module-root: toolchains/sysroot
          bazelisk-cache: true
          repository-cache: true
      - name: Build
        run: |
          cd toolchains/sysroot
          bazelisk build -c opt --curses=no --noshow_progress //:sysroot
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: toolchains/sysroot/bazel-bin/sysroot.tar.xz
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: toolchains/sysroot/bazel-bin/sysroot.tar.xz
          make_latest: false  # Don't clobber non-sysroot releases.
